CREATE TABLE SELLO_DISCOGRAFICO (
id_sello SERIAL NOT NULL,
nombre VARCHAR(127) NOT NULL,
CONSTRAINT PK_SELLO_DISCOGRAFICO PRIMARY KEY (id_sello)
);

CREATE TABLE ARTISTA_SELLO (
id_sello INT4 NOT NULL,
id_artista INT4 NOT NULL,
fecha_inicio DATE NULL,
fecha_termino DATE  NULL,
CONSTRAINT PK_ARTISTA_SELLO PRIMARY KEY (id_sello, id_artista)
);

CREATE TABLE ARTISTA(
id_artista SERIAL NOT NULL,
nombre VARCHAR(127) NOT NULL,
CONSTRAINT PK_ARTISTA PRIMARY KEY (id_artista)
);

CREATE TABLE ARTISTAS_SIMILARES(
	id_artista INT4 NOT NULL,
	id_artista_similar INT4 NOT NULL,
	CONSTRAINT PK_ARTISTAS_SIMILARES PRIMARY KEY (id_artista, id_artista_similar)
);

CREATE TABLE ALBUM(
	id_album SERIAL NOT NULL,
	id_artista INT4 NOT NULL,
	nombre VARCHAR(127) NOT NULL,
	descripcion VARCHAR(255) NULL,
	genero INT4 NOT NULL,
	id_sello INT4 NOT NULL,
	fecha_año VARCHAR(5) NOT NULL,
	CONSTRAINT PK_ALBUM PRIMARY KEY (id_album)
);

CREATE TABLE CANCION (
	id_cancion SERIAL NOT NULL,
	id_album INT4 NOT NULL,
	nombre VARCHAR(127) NOT NULL,
	duracion VARCHAR(10) NULL,
	CONSTRAINT PK_CANCION PRIMARY KEY (id_cancion)
);


CREATE TABLE ARTISTA_INVITADO_CANCION(
	id_cancion INT4 NOT NULL,
	id_artista_invitado INT4 NOT NULL,
	CONSTRAINT PK_ARTISTA_INVITADO_CANCION PRIMARY KEY (id_cancion, id_artista_invitado)
);


CREATE TABLE GENEROS_ARTISTA(
	id_artista INT4 NOT NULL,
	id_genero INT4 NOT NULL,
	CONSTRAINT PK_GENEROS_ARTISTA PRIMARY KEY (id_artista, id_genero)
);

CREATE TABLE GENERO(
	id_genero SERIAL NOT NULL,
	nombre VARCHAR(127) NOT NULL,
    CONSTRAINT PK_GENERO PRIMARY KEY (id_genero)
);


CREATE TABLE USUARIO (
	nombre_usuario VARCHAR(20) NOT NULL,
	nombre VARCHAR(127) NOT NULL,
	apellido VARCHAR(127) NOT NULL,
	pais VARCHAR(127) NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY (nombre_usuario)
);

CREATE TABLE ARTISTAS_FAVORITOS(
	nombre_usuario VARCHAR(20) NOT NULL,
	id_artista INT4 NOT NULL,
	CONSTRAINT PK_ARTISTAS_FAVORITOS PRIMARY KEY (nombre_usuario, id_artista)
);

CREATE TABLE LISTA_REPRODUCCION(
	id_lista SERIAL NOT NULL,
	nombre_lista VARCHAR(127) NOT NULL,
	nombre_usuario VARCHAR(20) NOT NULL,
    CONSTRAINT PK_LISTA_REPRODUCCION PRIMARY KEY (id_lista)
);

CREATE TABLE CANCIONES_LISTA (
	id_lista INT4 NOT NULL,
	id_cancion INT4 NOT NULL,
	CONSTRAINT PK_CANCIONES_LISTA PRIMARY KEY (id_lista, id_cancion)
);

CREATE TABLE LISTA_COMPARTIDA(
	id_lista INT4 NOT NULL,
	nombre_usuario VARCHAR(20) NOT NULL,
	CONSTRAINT PK_LISTA_COMPARTIDA PRIMARY KEY (id_lista, nombre_usuario)
);


ALTER TABLE ARTISTA_SELLO
	ADD CONSTRAINT FK_SELLO_TIENE_ARTISTAS FOREIGN KEY (id_artista)
		REFERENCES ARTISTA (id_artista)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ARTISTAS_SIMILARES
	ADD CONSTRAINT FK_SON_ARTISTAS_SIMILARES FOREIGN KEY (id_artista)
		REFERENCES ARTISTA (id_artista)
		ON DELETE RESTRICT ON UPDATE RESTRICT;
		
ALTER TABLE ARTISTAS_SIMILARES
	ADD CONSTRAINT FK_TIENE_ARTISTA_SIMILAR FOREIGN KEY (id_artista_similar)
		REFERENCES ARTISTA (id_artista)
		ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE ALBUM 
	ADD CONSTRAINT FK_ARTISTA_TIENE_ALBUMES FOREIGN KEY (id_artista)
		REFERENCES ARTISTA (id_artista)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ALBUM 
	ADD CONSTRAINT FK_ALBUM_TIENE_GENERO FOREIGN KEY (genero)
		REFERENCES GENERO (id_genero)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CANCION
	ADD CONSTRAINT FK_ALBUM_TIENE_CANCIONES FOREIGN KEY (id_album)
		REFERENCES ALBUM (id_album)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ARTISTA_INVITADO_CANCION 
	ADD CONSTRAINT FK_CANCION_TIENE_ARTISTA_INVITADO FOREIGN KEY (id_cancion)
		REFERENCES CANCION (id_cancion)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE GENEROS_ARTISTA
	ADD CONSTRAINT FK_ARTISTA_TIENE_GENERO FOREIGN KEY (id_artista)
		REFERENCES ARTISTA (id_artista)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE GENEROS_ARTISTA
	ADD CONSTRAINT FK_GENERO_TIENE_ARTISTA FOREIGN KEY (id_genero)
		REFERENCES GENERO (id_genero)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ARTISTAS_FAVORITOS
	ADD CONSTRAINT FK_USUARIO_TIENE_ARTISTA_FAVORITO FOREIGN KEY (nombre_usuario)
		REFERENCES USUARIO (nombre_usuario)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ARTISTAS_FAVORITOS
	ADD CONSTRAINT FK_ARTISTAS_GUARDADOS_POR_USUARIO FOREIGN KEY (id_artista)
		REFERENCES ARTISTA (id_artista)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LISTA_REPRODUCCION
	ADD CONSTRAINT FK_USUARIO_TIENE_LISTA FOREIGN KEY (nombre_usuario)
		REFERENCES USUARIO (nombre_usuario)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CANCIONES_LISTA
	ADD CONSTRAINT FK_CANCION_ESTA_EN_LISTA FOREIGN KEY (id_cancion)
		REFERENCES CANCION (id_cancion)
		ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LISTA_COMPARTIDA
	ADD CONSTRAINT FK_LISTA_COMPARTIDA_CON_USUARIOS FOREIGN KEY (id_lista)
		REFERENCES LISTA_REPRODUCCION (id_lista)
		ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE LISTA_COMPARTIDA
	ADD CONSTRAINT FK_USUARIOS_COMPARTEN_LISTA FOREIGN KEY (nombre_usuario)
		REFERENCES USUARIO (nombre_usuario)
		ON DELETE RESTRICT ON UPDATE RESTRICT;











